version: "3.9"

services:
  abnb-listing-matching:
    build:
        context: .  # will look for a Dockerfile under this directory
    container_name: abnb-listing-matching
    shm_size: '16gb'  #  Set for pytorch dataloader shared memory
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    restart: always
    ports:
      - "8288:8888"  # mapping host port 8288 to container port 8888 for jupyter
      - "8388:8988"  # mapping host port 8388 to container port 8888 for fastapi

    network_mode: "bridge"
    expose: 
        - "8888" 
        - "8988"
    volumes:
        - "/home/makan/Documents/projects/abnb-listing-matching/abnb-listing-matching:/home/appuser/code"
        - "/home/makan/Documents/projects/abnb-listing-matching/data:/home/appuser/data"
        - "/home/makan/Documents/projects/abnb-listing-matching/artifacts:/home/appuser/artifacts"
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all